// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCABLutsPzYACaRrYQqVWTe_Zpgj7LvXZI',
    appId: '1:477602692636:web:db46a301924254fcdda9d9',
    messagingSenderId: '477602692636',
    projectId: 'agendamento-de-centrais',
    authDomain: 'agendamento-de-centrais.firebaseapp.com',
    storageBucket: 'agendamento-de-centrais.firebasestorage.app',
    measurementId: 'G-Y6VQGWHG56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCpln_lxF1E1arLItgFHoedSeQR5StX4Y',
    appId: '1:477602692636:android:368c5a048de4d823dda9d9',
    messagingSenderId: '477602692636',
    projectId: 'agendamento-de-centrais',
    storageBucket: 'agendamento-de-centrais.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCABLutsPzYACaRrYQqVWTe_Zpgj7LvXZI',
    appId: '1:477602692636:web:5c9d2ecfa80e4658dda9d9',
    messagingSenderId: '477602692636',
    projectId: 'agendamento-de-centrais',
    authDomain: 'agendamento-de-centrais.firebaseapp.com',
    storageBucket: 'agendamento-de-centrais.firebasestorage.app',
    measurementId: 'G-M7BD4745DF',
  );
}
